spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/litemall?useSSL=true&useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF%2D8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
